version: '3'

services:
  frontend:
    build: ../../frontend-example-docker
    environment:
      VIRTUAL_HOST: colasloth.com
    depends_on:
      - backend
  backend:
    build: ../../backend-example-docker
    environment:
      REDIS: redis
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: backend_db
      DB_HOST: db
      FRONT_URL: http://localhost
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: backend_db
  nginx:
    image: nginx
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
