FROM ubuntu

COPY . /app

WORKDIR /app

RUN apt-get update &&\
	apt-get install curl -y &&\
	curl -sL https://deb.nodesource.com/setup_10.x | bash &&\
	apt-get install nodejs -y &&\
	apt-get purge curl -y &&\
	rm -rf /var/lib/apt/lists/* &&\
	npm install &&\
	useradd -m app &&\
	chown -R app /app

USER app
    
ENV FRONT_URL="http://localhost:5000"

CMD ["npm", "start"]

EXPOSE 8000
