FROM ubuntu

COPY . /app

WORKDIR /app

ENV FRONT_URL="http://localhost:5000"

RUN apt-get update &&\
	apt-get install curl ca-certificates -y &&\
	curl -sL https://deb.nodesource.com/setup_10.x | bash &&\
	apt-get install nodejs -y &&\
	apt-get purge -y --auto-remove curl &&\
	rm -rf /var/lib/apt/lists/* &&\
	npm install
    
CMD ["npm", "start"]

EXPOSE 8000
